(()=>{'use strict';
const $=id=>document.getElementById(id);
const COLORS={blank:'#fffdf5',street:'#9dbca0',station:'#a9b7c3',electricity:'#e4cf81',water:'#91c8d4',utility:'#a4c8c7',tax:'#ead5a0',chance:'#f0c28d',community:'#b7d5b5',start:'#dce8d1',parking:'#dce8d1',jail:'#e4e6df',gotojail:'#e4c4b7',custom:'#c7bce0'};
const LABELS={blank:'Empty space',street:'Street / property',station:'Station',electricity:'Electricity company',water:'Water company',utility:'Other utility',tax:'Tax / fee',chance:'Chance / event',community:'Community chest',start:'Start',parking:'Free parking',jail:'Jail',gotojail:'Go to jail',custom:'Custom special'};
const STORE='boardwright-studio-v3';
let count=40,tiles=[],selected=0,centerImage='',undoStack=[],redoStack=[],historyBusy=false,saveTimer=null;
const blankTile=i=>({pos:i,name:'',type:'blank',price:'',color:COLORS.blank,icon:'',image:''});
function initial(n){return Array.from({length:n},(_,i)=>blankTile(i))}
function clone(x){return JSON.parse(JSON.stringify(x))}
function currentState(){return {count,tiles:clone(tiles),selected,centerImage,edition:$('edition').value,subtitle:$('subtitle').value,accent:$('accent').value}}
function pushHistory(){if(historyBusy)return;undoStack.push(currentState());if(undoStack.length>60)undoStack.shift();redoStack=[];updateUndoButtons()}
function restore(s){historyBusy=true;count=s.count;tiles=clone(s.tiles);selected=Math.min(s.selected,count-1);centerImage=s.centerImage||'';$('edition').value=s.edition||'';$('subtitle').value=s.subtitle||'';$('accent').value=s.accent||'#173b2e';$('layoutSelect').value=String(count);setPreview('centerThumb',centerImage);fillEditor();render();historyBusy=false;autoSave()}
function undo(){if(!undoStack.length)return;redoStack.push(currentState());const s=undoStack.pop();restore(s);updateUndoButtons();toast('Undo complete')}
function redo(){if(!redoStack.length)return;undoStack.push(currentState());const s=redoStack.pop();restore(s);updateUndoButtons();toast('Redo complete')}
function updateUndoButtons(){$('undoBtn').disabled=!undoStack.length;$('redoBtn').disabled=!redoStack.length}
function showToast(msg){const t=$('toast');t.textContent=msg;t.style.display='block';clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.style.display='none',2200)}
function setStatus(s){$('status').textContent=s}
function autoSave(){setStatus('Unsaved changes…');clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveToStorage(true),350)}
function saveToStorage(silent){try{localStorage.setItem(STORE,JSON.stringify(projectData()));setStatus('Saved on this device');if(!silent)showToast('Project saved on this device')}catch(e){setStatus('Storage full — export a JSON backup');if(!silent)alert('Could not save in browser storage. Try smaller images or export a JSON backup.')}} 
function projectData(){return {app:'Boardwright',version:3,count,tiles,centerImage,edition:$('edition').value,subtitle:$('subtitle').value,accent:$('accent').value}}
function loadFromStorage(){try{const raw=localStorage.getItem(STORE);if(!raw)return false;return applyProject(JSON.parse(raw),false)}catch(e){return false}}
function applyProject(d,notify=true){if(!d||!Array.isArray(d.tiles)||![28,40].includes(Number(d.count))||d.tiles.length!==Number(d.count))throw Error('This is not a valid Boardwright project.');count=Number(d.count);tiles=initial(count);d.tiles.forEach((t,i)=>{if(!t||!Number.isInteger(Number(t.pos))||t.pos<0||t.pos>=count)return;tiles[t.pos]={...blankTile(t.pos),...t,pos:t.pos}});centerImage=d.centerImage||'';$('edition').value=d.edition||'MY CUSTOM EDITION';$('subtitle').value=d.subtitle||'';$('accent').value=d.accent||'#173b2e';$('layoutSelect').value=String(count);selected=Math.min(Number(d.selected)||0,count-1);setPreview('centerThumb',centerImage);fillEditor();render();saveToStorage(true);if(notify)showToast('Project loaded');return true}
function saveProjectFile(){saveToStorage(true);download(new Blob([JSON.stringify(projectData(),null,2)],{type:'application/json'}),slug($('edition').value)+'-boardwright.json')}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function slug(s){return String(s||'boardwright-board').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'boardwright-board'}
function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setPreview(id,src){const img=$(id);if(src){img.src=src;img.style.display='block'}else{img.removeAttribute('src');img.style.display='none'}}
function typeColor(t){return COLORS[t]||COLORS.custom}
function posName(i){return ['Bottom edge · right to left','Left edge · bottom to top','Top edge · left to right','Right edge · top to bottom'][side(i)]}
function side(i){if(count===40){if(i<=10)return 0;if(i<=20)return 1;if(i<=30)return 2;return 3}if(i<=7)return 0;if(i<=14)return 1;if(i<=21)return 2;return 3}
function gridPosition(i){const tracks=count===40?13:9;if(count===40){if(i===0)return {r:12,c:12,rs:2,cs:2};if(i<10)return {r:12,c:12-i,rs:2,cs:1};if(i===10)return {r:12,c:1,rs:2,cs:2};if(i<20)return {r:22-i,c:1,rs:1,cs:2};if(i===20)return {r:1,c:1,rs:2,cs:2};if(i<30)return {r:1,c:i-18,rs:2,cs:1};if(i===30)return {r:1,c:12,rs:2,cs:2};return {r:i-28,c:12,rs:1,cs:2}}else{if(i===0)return {r:9,c:9,rs:2,cs:2};if(i<7)return {r:9,c:10-i,rs:2,cs:1};if(i===7)return {r:9,c:1,rs:2,cs:2};if(i<14)return {r:16-i,c:1,rs:1,cs:2};if(i===14)return {r:1,c:1,rs:2,cs:2};if(i<21)return {r:1,c:i-11,rs:2,cs:1};if(i===21)return {r:1,c:9,rs:2,cs:2};return {r:i-19,c:9,rs:1,cs:2}}}
function isCorner(i){return count===40?[0,10,20,30].includes(i):[0,7,14,21].includes(i)}
function tileTitle(i){return `Square ${i+1}${isCorner(i)?' · Corner':''}`}
function fillEditor(){const t=tiles[selected]||blankTile(selected);$('selectedTitle').textContent=tileTitle(selected);$('selectedCount').textContent=`${selected+1} / ${count}`;$('spaceName').value=t.name||'';$('spaceType').value=t.type||'blank';$('spacePrice').value=t.price||'';$('spaceColor').value=t.color||typeColor(t.type);$('spaceIcon').value=t.icon||'';setPreview('tileThumb',t.image||'')}
function render(){const b=$('board');b.innerHTML='';const sideN=count===40?13:10,centerEnd=sideN-1;b.style.setProperty('--n',sideN);b.style.gridTemplateColumns=`repeat(${sideN},minmax(0,1fr))`;b.style.gridTemplateRows=`repeat(${sideN},minmax(0,1fr))`;
const center=document.createElement('div');center.className='center'+(centerImage?' hasphoto':'');center.style.gridColumn=`3/${centerEnd}`;center.style.gridRow=`3/${centerEnd}`;center.innerHTML='<div class="centerkicker">A CUSTOM BOARD GAME</div><img class="centerphoto" alt=""><h3></h3><div class="rule"></div><p></p>';if(centerImage){center.querySelector('img').src=centerImage}center.querySelector('h3').textContent=$('edition').value||'YOUR EDITION';center.querySelector('h3').style.color=$('accent').value;center.querySelector('p').textContent=$('subtitle').value;b.appendChild(center);
tiles.forEach((t,i)=>{const gp=gridPosition(i),el=document.createElement('button');el.type='button';el.className='tile'+(isCorner(i)?' corner':'')+(i===selected?' selected':'');el.style.gridRow=`${gp.r}/${gp.r+gp.rs}`;el.style.gridColumn=`${gp.c}/${gp.c+gp.cs}`;el.setAttribute('aria-label',`${tileTitle(i)}${t.name?': '+t.name:''}`);el.title=t.name||`Empty square ${i+1}`;if(t.type!=='blank'){const band=document.createElement('div');band.className='band';band.style.background=t.color||typeColor(t.type);el.appendChild(band)}if(t.image){const img=document.createElement('img');img.className='tilephoto';img.src=t.image;img.alt='';el.appendChild(img)}if(t.icon){const icon=document.createElement('div');icon.className='tileicon';icon.textContent=t.icon;el.appendChild(icon)}if(t.name){const nm=document.createElement('div');nm.className='tilename';nm.textContent=t.name;el.appendChild(nm)}else{const plus=document.createElement('div');plus.className='emptyplus';plus.textContent='+';el.appendChild(plus)}if(t.price){const price=document.createElement('div');price.className='tileprice';price.textContent=t.price;el.appendChild(price)}el.addEventListener('click',()=>{selected=i;fillEditor();render()});b.appendChild(el)});
$('geometryLabel').textContent=`${count} spaces · 4 corners`;$('boardStatus').textContent=`${tiles.length} independent squares · ${tiles.filter(t=>t.name||t.image).length} customised`;$('undoBtn').disabled=!undoStack.length;$('redoBtn').disabled=!redoStack.length}
function applyEditor(){pushHistory();const old=tiles[selected];tiles[selected]={...old,pos:selected,name:$('spaceName').value.trim(),type:$('spaceType').value,price:$('spacePrice').value.trim(),color:$('spaceColor').value,icon:$('spaceIcon').value.trim(),image:old.image||''};render();autoSave();showToast('Square updated')}
function clearSelected(){pushHistory();tiles[selected]=blankTile(selected);fillEditor();render();autoSave();showToast('Square cleared')}
function handleImage(file,which){if(!file)return;if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}if(file.size>2.5*1024*1024){alert('Choose an image smaller than 2.5 MB so it can save reliably.');return}const reader=new FileReader();reader.onerror=()=>alert('Could not read that image. Try another file.');reader.onload=()=>{pushHistory();if(which==='center'){centerImage=reader.result;setPreview('centerThumb',centerImage)}else{tiles[selected].image=reader.result;setPreview('tileThumb',tiles[selected].image)}render();autoSave();showToast('Photo added')};reader.readAsDataURL(file)}
function newBlank(){if(!confirm('Create a new blank board? Export a backup first if you need your current project.'))return;pushHistory();tiles=initial(count);centerImage='';selected=0;$('edition').value='MY CUSTOM EDITION';$('subtitle').value='';setPreview('centerThumb','');$('centerFile').value='';fillEditor();render();autoSave();showToast('New blank board created')}
function changeLayout(next){next=Number(next);if(next===count)return;const lost=tiles.filter(t=>t.pos>=next&&(t.name||t.image||t.icon||t.price));if(lost.length&&!confirm(`Changing layout will remove ${lost.length} customised square(s) outside the new ${next}-space board. Continue?`)){$('layoutSelect').value=String(count);return}pushHistory();if(next<count)tiles=tiles.filter(t=>t.pos<next);else{const old=new Map(tiles.map(t=>[t.pos,t]));tiles=Array.from({length:next},(_,i)=>old.get(i)||blankTile(i))}count=next;selected=Math.min(selected,count-1);fillEditor();render();autoSave()}
function svgExport(){const n=count===40?13:10,S=1600,cell=S/n,parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">`,`<rect width="${S}" height="${S}" fill="#294536"/>`];const centerX=2*cell,centerY=2*cell,centerSize=(n-4)*cell;parts.push(`<rect x="${centerX}" y="${centerY}" width="${centerSize}" height="${centerSize}" fill="#f4f4e9" stroke="#dfe5d8"/>`);if(centerImage){parts.push(`<image href="${centerImage}" x="${centerX}" y="${centerY}" width="${centerSize}" height="${centerSize}" preserveAspectRatio="xMidYMid slice"/>`);parts.push(`<rect x="${centerX}" y="${centerY}" width="${centerSize}" height="${centerSize}" fill="#000" opacity=".38"/>`);}const kickerY=centerY+centerSize*.30,titleY=centerY+centerSize*.52,ruleY=centerY+centerSize*.59,subY=centerY+centerSize*.68;const textColor=centerImage?'#ffffff':$('accent').value;parts.push(`<text x="${S/2}" y="${kickerY}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${S*.014}" font-weight="700" letter-spacing="5" fill="${centerImage?'#ffffff':'#718073'}">A CUSTOM BOARD GAME</text>`);parts.push(`<text x="${S/2}" y="${titleY}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${Math.min(64,S*.05)}" font-weight="800" fill="${textColor}">${safe($('edition').value||'YOUR EDITION')}</text>`);parts.push(`<rect x="${S/2-S*.03}" y="${ruleY}" width="${S*.06}" height="5" rx="2" fill="#d8b55d"/>`);parts.push(`<text x="${S/2}" y="${subY}" text-anchor="middle" font-family="Arial,sans-serif" font-size="22" fill="${centerImage?'#ffffff':'#6a766e'}">${safe($('subtitle').value)}</text>`);
tiles.forEach((t,i)=>{const p=gridPosition(i),x=(p.c-1)*cell,y=(p.r-1)*cell,w=p.cs*cell-2,h=p.rs*cell-2;parts.push(`<rect x="${x+1}" y="${y+1}" width="${w}" height="${h}" fill="${isCorner(i)?'#e6eddf':'#fffdf5'}" stroke="#bfcabf" stroke-width="2"/>`);if(t.type!=='blank')parts.push(`<rect x="${x+3}" y="${y+3}" width="${w-4}" height="${Math.min(w,h)*.13}" fill="${t.color||typeColor(t.type)}"/>`);if(t.image)parts.push(`<image href="${t.image}" x="${x+w*.2}" y="${y+h*.18}" width="${w*.6}" height="${h*.36}" preserveAspectRatio="xMidYMid meet"/>`);if(t.icon)parts.push(`<text x="${x+w/2}" y="${y+h*.45}" text-anchor="middle" font-size="${cell*.18}">${safe(t.icon)}</text>`);if(t.name){const words=t.name.split(/\s+/);let lines=[],line='';words.forEach(word=>{if((line+' '+word).trim().length>14&&line){lines.push(line);line=word}else line=(line+' '+word).trim()});if(line)lines.push(line);lines.slice(0,4).forEach((l,j)=>parts.push(`<text x="${x+w/2}" y="${y+h*(t.image?.68:.57)+j*h*.085}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${count===40?Math.min(15,w*.12):Math.min(19,w*.14)}" font-weight="700" fill="#1c2922">${safe(l)}</text>`))}if(t.price)parts.push(`<text x="${x+w/2}" y="${y+h*.94}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${Math.min(14,w*.11)}" fill="#637065">${safe(t.price)}</text>`)});parts.push('</svg>');return parts.join('')}
function exportSvg(){download(new Blob([svgExport()],{type:'image/svg+xml;charset=utf-8'}),slug($('edition').value)+'.svg');showToast('SVG board exported')}
function exportPng(){const svg=svgExport(),blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=2000;c.height=2000;const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(png=>{if(png){download(png,slug($('edition').value)+'.png');showToast('PNG board exported')}else alert('Could not export PNG in this browser.')},'image/png')};img.onerror=()=>{URL.revokeObjectURL(url);alert('Could not create PNG. Try SVG export instead.')};img.src=url}
function exportMenu(){const choice=prompt('Export board as:\n1 = PNG image\n2 = SVG image\n3 = Print / Save as PDF\n4 = Project JSON backup','1');if(choice==='1')exportPng();else if(choice==='2')exportSvg();else if(choice==='3')window.print();else if(choice==='4')saveProjectFile()}
$('applyBtn').addEventListener('click',applyEditor);$('clearTileBtn').addEventListener('click',clearSelected);$('undoBtn').addEventListener('click',undo);$('redoBtn').addEventListener('click',redo);$('newBtn').addEventListener('click',newBlank);$('saveBtn').addEventListener('click',()=>saveToStorage(false));$('saveProjectBtn').addEventListener('click',saveProjectFile);$('loadProjectBtn').addEventListener('click',()=>{const inp=document.createElement('input');inp.type='file';inp.accept='.json,application/json';inp.onchange=()=>{if(inp.files[0])readJson(inp.files[0])};inp.click()});$('jsonBtn').addEventListener('click',saveProjectFile);$('exportBtn').addEventListener('click',exportMenu);$('layoutSelect').addEventListener('change',e=>changeLayout(e.target.value));$('centerFile').addEventListener('change',e=>{handleImage(e.target.files[0],'center');e.target.value=''});$('tileFile').addEventListener('change',e=>{handleImage(e.target.files[0],'tile');e.target.value=''});$('removeCenter').addEventListener('click',()=>{if(!centerImage)return;pushHistory();centerImage='';setPreview('centerThumb','');render();autoSave()});$('removeTilePhoto').addEventListener('click',()=>{if(!tiles[selected].image)return;pushHistory();tiles[selected].image='';setPreview('tileThumb','');render();autoSave()});$('accent').addEventListener('input',()=>{pushHistory();render();autoSave()});['edition','subtitle'].forEach(id=>$(id).addEventListener('input',()=>{render();autoSave()}));$('spaceType').addEventListener('change',()=>{$('spaceColor').value=typeColor($('spaceType').value)});$('jsonFile').addEventListener('change',e=>{if(e.target.files[0])readJson(e.target.files[0]);e.target.value=''});
function readJson(file){const r=new FileReader();r.onerror=()=>alert('Could not read that file.');r.onload=()=>{try{const d=JSON.parse(r.result);pushHistory();applyProject(d,true)}catch(err){alert(err.message||'Invalid project file.')}};r.readAsText(file)}
// Start with a genuinely blank, fully populated geometry: 40 selectable tile elements.
tiles=initial(40);selected=0;
if(!loadFromStorage()){render();fillEditor();saveToStorage(true)}else{render();fillEditor()}
updateUndoButtons();
})();
