const $=id=>document.getElementById(id);const colors={brown:'#95502f',lightblue:'#9bd8ed',pink:'#d85a9b',orange:'#f28a32',red:'#e94b45',yellow:'#f3d84c',green:'#269b61',blue:'#3676c8'};
const initial=[
['GO','corner',''],['Mediterranean Avenue','street','brown',60],['Community Chest','card',''],['Baltic Avenue','street','brown',60],['Income Tax','tax','',null],['Reading Railroad','station','',200],['Oriental Avenue','street','lightblue',100],['Chance','chance',''],['Vermont Avenue','street','lightblue',100],['Connecticut Avenue','street','lightblue',120],
['Jail / Just Visiting','corner',''],['St. Charles Place','street','pink',140],['Electric Company','utility','',150],['States Avenue','street','pink',140],['Virginia Avenue','street','pink',160],['Pennsylvania Railroad','station','',200],['St. James Place','street','orange',180],['Community Chest','card',''],['Tennessee Avenue','street','orange',180],['New York Avenue','street','orange',200],
['Free Parking','corner',''],['Kentucky Avenue','street','red',220],['Chance','chance',''],['Indiana Avenue','street','red',220],['Illinois Avenue','street','red',240],['B. & O. Railroad','station','',200],['Atlantic Avenue','street','yellow',260],['Ventnor Avenue','street','yellow',260],['Water Works','utility','',150],['Marvin Gardens','street','yellow',280],
['Go To Jail','corner',''],['Pacific Avenue','street','green',300],['North Carolina Avenue','street','green',300],['Community Chest','card',''],['Pennsylvania Avenue','street','green',320],['Short Line','station','',200],['Chance','chance',''],['Park Place','street','blue',350],['Luxury Tax','tax','',null],['Boardwalk','street','blue',400]];
let spaces=initial.map((a,i)=>({id:i,name:a[0],type:a[1],color:a[2],price:a[3]})),selected=1,bgData='',undo=[],redo=[];
const sides=[{ids:[30,31,32,33,34,35,36,37,38,39],pos:'top'},{ids:[20,19,18,17,16,15,14,13,12,11],pos:'left'},{ids:[10,9,8,7,6,5,4,3,2,1],pos:'bottom'},{ids:[0,39,38,37,36,35,34,33,32,31],pos:'right'}];
// Place the canonical perimeter: bottom left-to-right is spaces 10-19, right bottom-to-top 20-29, top right-to-left 30-39, left top-to-bottom 0-9.
function position(i){if(i<=10)return {r:11,c:11-i,side:'bottom'};if(i<=20)return {r:21-i,c:1,side:'left'};if(i<=30)return {r:1,c:i-19,side:'top'};return {r:i-29,c:11,side:'right'}}
function typeLabel(s){return ({street:'Street property',station:'Station',utility:'Utility',card:'Card space',chance:'Chance space',tax:'Tax space',corner:'Corner'})[s.type]||'Space'}
function snap(){undo.push(JSON.stringify({spaces,bgData,title:$('boardTitle').value,subtitle:$('boardSubtitle').value}));if(undo.length>40)undo.shift();redo=[];buttons()}
function buttons(){$('undoBtn').disabled=!undo.length;$('redoBtn').disabled=!redo.length}
function render(){const board=$('board');board.querySelectorAll('.tile,.corner').forEach(n=>n.remove());$('centerTitle').textContent=$('boardTitle').value||'MONOPOLY';$('centerSubtitle').textContent=$('boardSubtitle').value;$('centerImage').style.backgroundImage=bgData?`url("${bgData}")`:'none';
spaces.forEach(s=>{if(s.type==='corner')return;let r,c,side;if(s.id>=1&&s.id<=9){side='bottom';r=10;c=11-s.id}else if(s.id>=11&&s.id<=19){side='left';r=21-s.id;c=2}else if(s.id>=21&&s.id<=29){side='top';r=2;c=s.id-19}else if(s.id>=31&&s.id<=39){side='right';r=s.id-29;c=10}else{return};const el=document.createElement('button');el.type='button';el.className=`tile ${side}${selected===s.id?' selected':''}`;el.style.gridRow=r;el.style.gridColumn=c;el.style.setProperty('--band',colors[s.color]||'#ddd');const band=document.createElement('span');band.className='band';el.appendChild(band);const content=document.createElement('span');content.className='tileContent';const sym=s.type==='station'?'🚂':s.type==='utility'?(s.name==='Electric Company'?'⚡':'💧'):s.type==='chance'?'❔':s.type==='card'?'▤':s.type==='tax'?'$':'';if(sym)content.innerHTML=`<span class=\"symbol\">${sym}</span>`;content.append(document.createTextNode(s.name));if(s.price!=null){const pr=document.createElement('span');pr.className='price';pr.textContent='$'+s.price;content.appendChild(pr)}el.appendChild(content);el.addEventListener('click',()=>select(s.id));board.appendChild(el)});
const corners=[{id:0,cls:'go',r:11,c:11,icon:'➜',text:'GO'},{id:10,cls:'jail',r:11,c:1,icon:'🔒',text:'IN JAIL / JUST VISITING'},{id:20,cls:'parking',r:1,c:1,icon:'🅿',text:'FREE PARKING'},{id:30,cls:'gojail',r:1,c:11,icon:'👮',text:'GO TO JAIL'}];corners.forEach(c=>{const el=document.createElement('div');el.className='corner '+c.cls;el.style.gridRow=c.r;el.style.gridColumn=c.c;el.innerHTML=`<div><span class="cornerIcon">${c.icon}</span>${c.text}</div>`;board.appendChild(el)});
// Explicit fixed grid placement for the 36 non-corner spaces, matching the four sides.
const tiles=[...board.querySelectorAll('.tile')];tiles.forEach(el=>{const id=Number(spaces.find(s=>s.name===el.querySelector('.tileContent')?.textContent)?.id);});}
function select(id){if(![...spaces].some(s=>s.id===id&&['street','station','utility'].includes(s.type)))return;selected=id;const s=spaces[id];$('selectedName').textContent=s.name;$('selectedType').textContent=typeLabel(s);$('spaceName').value=s.name;$('spacePrice').value=s.price??'';render()}
function updateSpace(){const s=spaces[selected];if(!s||!['street','station','utility'].includes(s.type))return;s.name=$('spaceName').value||'Unnamed property';s.price=$('spacePrice').value===''?null:Math.max(0,Number($('spacePrice').value)||0);$('selectedName').textContent=s.name;snap();render()}
$('spaceName').addEventListener('change',()=>{snap();updateSpace()});$('spacePrice').addEventListener('change',()=>{snap();updateSpace()});['boardTitle','boardSubtitle'].forEach(id=>$(id).addEventListener('input',render));$('bgUpload').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){toast('Choose an image file.');return}if(f.size>2.5*1024*1024){toast('That image is over 2.5 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{snap();bgData=reader.result;render()};reader.readAsDataURL(f)});$('removeImage').onclick=()=>{snap();bgData='';$('bgUpload').value='';render()};
$('resetBtn').onclick=()=>{snap();spaces=initial.map((a,i)=>({id:i,name:a[0],type:a[1],color:a[2],price:a[3]}));bgData='';$('boardTitle').value='MONOPOLY';$('boardSubtitle').value='';select(1);render();toast('Standard board restored')};$('saveBtn').onclick=()=>{const data={version:1,spaces,bgData,title:$('boardTitle').value,subtitle:$('boardSubtitle').value};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download='boardwright-project.json';a.click();URL.revokeObjectURL(a.href);toast('Project saved')};$('loadBtn').onclick=()=>$('loadFile').click();$('loadFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.spaces)||d.spaces.length!==40)throw Error();snap();spaces=d.spaces;bgData=d.bgData||'';$('boardTitle').value=d.title||'MONOPOLY';$('boardSubtitle').value=d.subtitle||'';select(1);render();toast('Project loaded')}catch{toast('That project file is not valid.')}};r.readAsText(f)};$('exportBtn').onclick=()=>exportPng();function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2300)}
$('undoBtn').onclick=()=>{if(!undo.length)return;redo.push(JSON.stringify({spaces,bgData,title:$('boardTitle').value,subtitle:$('boardSubtitle').value}));restore(undo.pop())};$('redoBtn').onclick=()=>{if(!redo.length)return;undo.push(JSON.stringify({spaces,bgData,title:$('boardTitle').value,subtitle:$('boardSubtitle').value}));restore(redo.pop())};function restore(raw){const d=JSON.parse(raw);spaces=d.spaces;bgData=d.bgData;$('boardTitle').value=d.title;$('boardSubtitle').value=d.subtitle;select(selected);buttons();render()}
function exportPng(){const N=1800,canvas=document.createElement('canvas');canvas.width=N;canvas.height=N;const ctx=canvas.getContext('2d');ctx.fillStyle='#dfe8d7';ctx.fillRect(0,0,N,N);const unit=N/11;ctx.strokeStyle='#17251e';ctx.lineWidth=3;ctx.fillStyle='#f9f8ef';function rect(c,r,w,h,fill){ctx.fillStyle=fill;ctx.fillRect(c*unit,r*unit,w*unit,h*unit);ctx.strokeRect(c*unit,r*unit,w*unit,h*unit)}
// center artwork behind title
rect(2,2,7,7,'#d9e3d4');const finish=()=>{ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 86px system-ui';ctx.fillStyle='#ffffff';ctx.shadowColor='#0009';ctx.shadowBlur=10;ctx.fillText(($('boardTitle').value||'MONOPOLY').slice(0,30),N/2,N/2-20,unit*6.5);ctx.font='32px system-ui';ctx.fillText($('boardSubtitle').value.slice(0,55),N/2,N/2+55,unit*6);ctx.shadowBlur=0;canvas.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='boardwright-board.png';a.click();URL.revokeObjectURL(a.href)},'image/png')};
const drawTiles=()=>{spaces.forEach(s=>{if(s.type==='corner')return;let c,r,w,h,side;if(s.id<=9){side='bottom';c=10-s.id;r=9;w=1;h=2}else if(s.id===10) return;else if(s.id<=19){side='left';c=0;r=19-s.id;w=2;h=1}else if(s.id<=29){side='top';c=s.id-20+1;r=0;w=1;h=2}else{side='right';c=9;r=s.id-30+1;w=2;h=1}rect(c,r,w,h,'#f9f8ef');ctx.fillStyle=colors[s.color]||'#d7e0d4';if(side==='bottom')ctx.fillRect(c*unit,r*unit,w*unit,.35*unit);else if(side==='top')ctx.fillRect(c*unit,(r+1.65)*unit,w*unit,.35*unit);else if(side==='left')ctx.fillRect(c*unit,r*unit,.35*unit,h*unit);else ctx.fillRect((c+1.65)*unit,r*unit,.35*unit,h*unit);ctx.fillStyle='#17251e';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 17px system-ui';ctx.save();if(side==='left'){ctx.translate(c*unit+unit,r*unit+unit/2);ctx.rotate(-Math.PI/2)}else if(side==='right'){ctx.translate((c+1)*unit,r*unit+unit/2);ctx.rotate(Math.PI/2)}let x=(c+w/2)*unit,y=(r+h/2)*unit;if(side==='bottom')y=r*unit+unit*1.1;if(side==='top')y=r*unit+unit*.9;if(side==='left'||side==='right'){x=(c+w/2)*unit;y=(r+h/2)*unit}ctx.fillText(s.name.slice(0,24),x,y,w*unit*.88);if(s.price!=null)ctx.fillText('$'+s.price,x,y+23,w*unit*.8);ctx.restore()});[['GO',9,9],['JAIL / VISITING',0,9],['FREE PARKING',0,0],['GO TO JAIL',9,0]].forEach(([t,c,r])=>{rect(c,r,2,2,'#f5f3e8');ctx.fillStyle='#17251e';ctx.font='bold 24px system-ui';ctx.textAlign='center';ctx.fillText(t,(c+1)*unit,(r+1)*unit)});const im=new Image();if(bgData){im.onload=()=>{ctx.drawImage(im,2*unit,2*unit,7*unit,7*unit);finish()};im.src=bgData}else finish()};drawTiles()}
// Set the center above tiles and correct placement with explicit perimeter index mapping.
render();select(1);